In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('data/raw/ISIC_2019_Test_GroundTruth.csv')
print(f"Số lượng ảnh ban đầu: {len(df)}")
df

Số lượng ảnh ban đầu: 8238

,image,MEL,NV,BCC,AK,BKL,DF,VASC,SCC,UNK,score_weight,validation_weight
0,ISIC_0034321,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,ISIC_0034322,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,ISIC_0034323,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,ISIC_0034324,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,ISIC_0034325,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8233,ISIC_0073236,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
8234,ISIC_0073243,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8235,ISIC_0073250,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8236,ISIC_0073252,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8237,ISIC_0073253,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [15]:
df.drop(['score_weight', 'validation_weight'], axis=1 ,inplace=True)

In [16]:
df

             image  MEL   NV  BCC   AK  BKL   DF  VASC  SCC  UNK
0     ISIC_0034321  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
1     ISIC_0034322  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
2     ISIC_0034323  0.0  0.0  1.0  0.0  0.0  0.0   0.0  0.0  0.0
3     ISIC_0034324  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
4     ISIC_0034325  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
...            ...  ...  ...  ...  ...  ...  ...   ...  ...  ...
8233  ISIC_0073236  0.0  0.0  0.0  0.0  0.0  0.0   0.0  1.0  0.0
8234  ISIC_0073243  0.0  0.0  1.0  0.0  0.0  0.0   0.0  0.0  0.0
8235  ISIC_0073250  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
8236  ISIC_0073252  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  1.0
8237  ISIC_0073253  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  1.0

[8238 rows x 10 columns]

In [17]:
import os
from pathlib import Path

In [18]:
IMAGE_FOLDER = Path('data/raw/ISIC_2019_Test_Input')

# Xóa các file ảnh có UNK = 1
unk_images = df[df['UNK'] == 1]['image'].tolist()
print(f"Số lượng ảnh UNK cần xóa: {len(unk_images)}")

deleted_count = 0
not_found_count = 0

for image_name in unk_images:
    for ext in ['.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG']:
        image_path = IMAGE_FOLDER / f"{image_name}{ext}"
        if image_path.exists():
            os.remove(image_path)
            deleted_count += 1
            print(f"Đã xóa: {image_path}")
            break
    else:
        not_found_count += 1
        print(f"Không tìm thấy: {image_name}")

print(f"\nTổng kết:")
print(f"  - Đã xóa: {deleted_count} ảnh")
print(f"  - Không tìm thấy: {not_found_count} ảnh")

Số lượng ảnh UNK cần xóa: 2047
Không tìm thấy: ISIC_0053455
Không tìm thấy: ISIC_0053461
Không tìm thấy: ISIC_0053465
Không tìm thấy: ISIC_0053468
Không tìm thấy: ISIC_0053486
Không tìm thấy: ISIC_0053548
Không tìm thấy: ISIC_0053587
Không tìm thấy: ISIC_0053590
Không tìm thấy: ISIC_0053592
Không tìm thấy: ISIC_0053598
Không tìm thấy: ISIC_0053606
Không tìm thấy: ISIC_0053607
Không tìm thấy: ISIC_0053608
Không tìm thấy: ISIC_0053624
Không tìm thấy: ISIC_0053633
Không tìm thấy: ISIC_0053638
Không tìm thấy: ISIC_0053646
Không tìm thấy: ISIC_0053662
Không tìm thấy: ISIC_0053676
Không tìm thấy: ISIC_0053687
Không tìm thấy: ISIC_0053701
Không tìm thấy: ISIC_0053703
Không tìm thấy: ISIC_0053705
Không tìm thấy: ISIC_0053707
Không tìm thấy: ISIC_0053709
Không tìm thấy: ISIC_0053727
Không tìm thấy: ISIC_0053730
Không tìm thấy: ISIC_0053737
Không tìm thấy: ISIC_0053745
Không tìm thấy: ISIC_0053767
Không tìm thấy: ISIC_0053802
Không tìm thấy: ISIC_0053806
Không tìm thấy: ISIC_0053808
Không tìm thấy: ISIC_0053822
Không tìm thấy: ISIC_0053832
Không tìm thấy: ISIC_0053834
Không tìm thấy: ISIC_0053855
Không tìm thấy: ISIC_0053856
Không tìm thấy: ISIC_0053864
Không tìm thấy: ISIC_0053869
Không tìm thấy: ISIC_0053887
Không tìm thấy: ISIC_0053897
Không tìm thấy: ISIC_0053907
Không tìm thấy: ISIC_0053911
Không tìm thấy: ISIC_0053938
Không tìm thấy: ISIC_0053955
Không tìm thấy: ISIC_0053958
Không tìm thấy: ISIC_0053962
Không tìm thấy: ISIC_0053963
Không tìm thấy: ISIC_0053964
Không tìm thấy: ISIC_0053966
Không tìm thấy: ISIC_0053977
Không tìm thấy: ISIC_0053979
Không tìm thấy: ISIC_0053994
Không tìm thấy: ISIC_0053999
Không tìm thấy: ISIC_0054028
Không tìm thấy: ISIC_0054029
Không tìm thấy: ISIC_0054068
Không tìm thấy: ISIC_0054072
Không tìm thấy: ISIC_0054091
Không tìm thấy: ISIC_0054099
Không tìm thấy: ISIC_0054102
Không tìm thấy: ISIC_0054124
Không tìm thấy: ISIC_0054125
Không tìm thấy: ISIC_0054136
Không tìm thấy: ISIC_0054143
Không tìm thấy: ISIC_0054152
Không tìm thấy: ISIC_0054164
Không tìm thấy: ISIC_0054177
Không tìm thấy: ISIC_0054180
Không tìm thấy: ISIC_0054182
Không tìm thấy: ISIC_0054195
Không tìm thấy: ISIC_0054196
Không tìm thấy: ISIC_0054216
Không tìm thấy: ISIC_0054225
Không tìm thấy: ISIC_0054228
Không tìm thấy: ISIC_0054250
Không tìm thấy: ISIC_0054267
Không tìm thấy: ISIC_0054283
Không tìm thấy: ISIC_0054303
Không tìm thấy: ISIC_0054319
Không tìm thấy: ISIC_0054321
Không tìm thấy: ISIC_0054323
Không tìm thấy: ISIC_0054361
Không tìm thấy: ISIC_0054363
Không tìm thấy: ISIC_0054367
Không tìm thấy: ISIC_0054372
Không tìm thấy: ISIC_0054374
Không tìm thấy: ISIC_0054426
Không tìm thấy: ISIC_0054429
Không tìm thấy: ISIC_0054431
Không tìm thấy: ISIC_0054452
Không tìm thấy: ISIC_0054455
Không tìm thấy: ISIC_0054469
Không tìm thấy: ISIC_0054471
Không tìm thấy: ISIC_0054474
Không tìm thấy: ISIC_0054479
Không tìm thấy: ISIC_0054489
Không tìm thấy: ISIC_0054490
Không tìm thấy: ISIC_0054496
Không tìm thấy: ISIC_0054503
Không tìm thấy: ISIC_0054519
Không tìm thấy: ISIC_0054526
Không tìm thấy: ISIC_0054529
Không tìm thấy: ISIC_0054534
Không tìm thấy: ISIC_0054561
Không tìm thấy: ISIC_0054571
Không tìm thấy: ISIC_0054585
Không tìm thấy: ISIC_0054590
Không tìm thấy: ISIC_0054601
Không tìm thấy: ISIC_0054603
Không tìm thấy: ISIC_0054611
Không tìm thấy: ISIC_0054613
Không tìm thấy: ISIC_0054617
Không tìm thấy: ISIC_0054628
Không tìm thấy: ISIC_0054636
Không tìm thấy: ISIC_0054638
Không tìm thấy: ISIC_0054646
Không tìm thấy: ISIC_0054648
Không tìm thấy: ISIC_0054667
Không tìm thấy: ISIC_0054678
Không tìm thấy: ISIC_0054679
Không tìm thấy: ISIC_0054680
Không tìm thấy: ISIC_0054681
Không tìm thấy: ISIC_0054686
Không tìm thấy: ISIC_0054699
Không tìm thấy: ISIC_0054712
Không tìm thấy: ISIC_0054733
Không tìm thấy: ISIC_0054742
Không tìm thấy: ISIC_0054750
Không tìm thấy: ISIC_0054762
Không tìm thấy: ISIC_0054769
Không tìm thấy: ISIC_0054785
Không tìm thấy: ISIC_0054786
Không tìm thấy: ISIC_0054791
Không tìm thấy: ISIC_0054801
Không tìm thấy: ISIC_0054806
Không tìm thấy: ISIC_0054812
Không tìm thấy: ISIC_0054818
Không tìm thấy: ISIC_0054822
Không tìm thấy: ISIC_0054824
Không tìm thấy: ISIC_0054837
Không tìm thấy: ISIC_0054839
Không tìm thấy: ISIC_0054862
Không tìm thấy: ISIC_0054863
Không tìm thấy: ISIC_0054872
Không tìm thấy: ISIC_0054875
Không tìm thấy: ISIC_0054876
Không tìm thấy: ISIC_0054883
Không tìm thấy: ISIC_0054922
Không tìm thấy: ISIC_0054926
Không tìm thấy: ISIC_0054945
Không tìm thấy: ISIC_0054950
Không tìm thấy: ISIC_0054966
Không tìm thấy: ISIC_0054984
Không tìm thấy: ISIC_0054987
Không tìm thấy: ISIC_0054989
Không tìm thấy: ISIC_0054992
Không tìm thấy: ISIC_0054997
Không tìm thấy: ISIC_0054999
Không tìm thấy: ISIC_0055011
Không tìm thấy: ISIC_0055012
Không tìm thấy: ISIC_0055017
Không tìm thấy: ISIC_0055020
Không tìm thấy: ISIC_0055023
Không tìm thấy: ISIC_0055026
Không tìm thấy: ISIC_0055028
Không tìm thấy: ISIC_0055029
Không tìm thấy: ISIC_0055040
Không tìm thấy: ISIC_0055041
Không tìm thấy: ISIC_0055045
Không tìm thấy: ISIC_0055055
Không tìm thấy: ISIC_0055070
Không tìm thấy: ISIC_0055078
Không tìm thấy: ISIC_0055082
Không tìm thấy: ISIC_0055084
Không tìm thấy: ISIC_0055088
Không tìm thấy: ISIC_0055093
Không tìm thấy: ISIC_0055094
Không tìm thấy: ISIC_0055101
Không tìm thấy: ISIC_0055113
Không tìm thấy: ISIC_0055115
Không tìm thấy: ISIC_0055142
Không tìm thấy: ISIC_0055145
Không tìm thấy: ISIC_0055160
Không tìm thấy: ISIC_0055162
Không tìm thấy: ISIC_0055170
Không tìm thấy: ISIC_0055171
Không tìm thấy: ISIC_0055190
Không tìm thấy: ISIC_0055192
Không tìm thấy: ISIC_0055210
Không tìm thấy: ISIC_0055216
Không tìm thấy: ISIC_0055220
Không tìm thấy: ISIC_0055238
Không tìm thấy: ISIC_0055252
Không tìm thấy: ISIC_0055281
Không tìm thấy: ISIC_0055288
Không tìm thấy: ISIC_0055300
Không tìm thấy: ISIC_0055333
Không tìm thấy: ISIC_0055339
Không tìm thấy: ISIC_0055345
Không tìm thấy: ISIC_0055360
Không tìm thấy: ISIC_0055366
Không tìm thấy: ISIC_0055373
Không tìm thấy: ISIC_0055383
Không tìm thấy: ISIC_0055386
Không tìm thấy: ISIC_0055430
Không tìm thấy: ISIC_0055432
Không tìm thấy: ISIC_0055445
Không tìm thấy: ISIC_0055456
Không tìm thấy: ISIC_0055457
Không tìm thấy: ISIC_0055466
Không tìm thấy: ISIC_0055482
Không tìm thấy: ISIC_0055508
Không tìm thấy: ISIC_0055515
Không tìm thấy: ISIC_0055530
Không tìm thấy: ISIC_0055531
Không tìm thấy: ISIC_0055532
Không tìm thấy: ISIC_0055538
Không tìm thấy: ISIC_0055545
Không tìm thấy: ISIC_0055558
Không tìm thấy: ISIC_0055565
Không tìm thấy: ISIC_0055568
Không tìm thấy: ISIC_0055573
Không tìm thấy: ISIC_0055576
Không tìm thấy: ISIC_0055580
Không tìm thấy: ISIC_0055588
Không tìm thấy: ISIC_0055597
Không tìm thấy: ISIC_0055605
Không tìm thấy: ISIC_0055607
Không tìm thấy: ISIC_0055617
Không tìm thấy: ISIC_0055632
Không tìm thấy: ISIC_0055644
Không tìm thấy: ISIC_0055646
Không tìm thấy: ISIC_0055651
Không tìm thấy: ISIC_0055652
Không tìm thấy: ISIC_0055654
Không tìm thấy: ISIC_0055655
Không tìm thấy: ISIC_0055662
Không tìm thấy: ISIC_0055666
Không tìm thấy: ISIC_0055674
Không tìm thấy: ISIC_0055678
Không tìm thấy: ISIC_0055683
Không tìm thấy: ISIC_0055687
Không tìm thấy: ISIC_0055694
Không tìm thấy: ISIC_0055704
Không tìm thấy: ISIC_0055710
Không tìm thấy: ISIC_0055725
Không tìm thấy: ISIC_0055734
Không tìm thấy: ISIC_0055750
Không tìm thấy: ISIC_0055757
Không tìm thấy: ISIC_0055770
Không tìm thấy: ISIC_0055782
Không tìm thấy: ISIC_0055786
Không tìm thấy: ISIC_0055794
Không tìm thấy: ISIC_0055798
Không tìm thấy: ISIC_0055831
Không tìm thấy: ISIC_0055837
Không tìm thấy: ISIC_0055843
Không tìm thấy: ISIC_0055847
Không tìm thấy: ISIC_0055857
Không tìm thấy: ISIC_0055869
Không tìm thấy: ISIC_0055884
Không tìm thấy: ISIC_0055933
Không tìm thấy: ISIC_0055965
Không tìm thấy: ISIC_0055975
Không tìm thấy: ISIC_0055978
Không tìm thấy: ISIC_0055998
Không tìm thấy: ISIC_0056006
Không tìm thấy: ISIC_0056018
Không tìm thấy: ISIC_0056028
Không tìm thấy: ISIC_0056034
Không tìm thấy: ISIC_0056043
Không tìm thấy: ISIC_0056057
Không tìm thấy: ISIC_0056060
Không tìm thấy: ISIC_0056066
Không tìm thấy: ISIC_0056069
Không tìm thấy: ISIC_0056080
Không tìm thấy: ISIC_0056084
Không tìm thấy: ISIC_0056086
Không tìm thấy: ISIC_0056090
Không tìm thấy: ISIC_0056091
Không tìm thấy: ISIC_0056098
Không tìm thấy: ISIC_0056120
Không tìm thấy: ISIC_0056121
Không tìm thấy: ISIC_0056123
Không tìm thấy: ISIC_0056137
Không tìm thấy: ISIC_0056143
Không tìm thấy: ISIC_0056148
Không tìm thấy: ISIC_0056158
Không tìm thấy: ISIC_0056160
Không tìm thấy: ISIC_0056161
Không tìm thấy: ISIC_0056162
Không tìm thấy: ISIC_0056169
Không tìm thấy: ISIC_0056191
Không tìm thấy: ISIC_0056198
Không tìm thấy: ISIC_0056199
Không tìm thấy: ISIC_0056215
Không tìm thấy: ISIC_0056216
Không tìm thấy: ISIC_0056227
Không tìm thấy: ISIC_0056230
Không tìm thấy: ISIC_0056238
Không tìm thấy: ISIC_0056268
Không tìm thấy: ISIC_0056285
Không tìm thấy: ISIC_0056289
Không tìm thấy: ISIC_0056299
Không tìm thấy: ISIC_0056300
Không tìm thấy: ISIC_0056318
Không tìm thấy: ISIC_0056320
Không tìm thấy: ISIC_0056352
Không tìm thấy: ISIC_0056361
Không tìm thấy: ISIC_0056367
Không tìm thấy: ISIC_0056375
Không tìm thấy: ISIC_0056385
Không tìm thấy: ISIC_0056386
Không tìm thấy: ISIC_0056388
Không tìm thấy: ISIC_0056390
Không tìm thấy: ISIC_0056462
Không tìm thấy: ISIC_0056465
Không tìm thấy: ISIC_0056471
Không tìm thấy: ISIC_0056475
Không tìm thấy: ISIC_0056489
Không tìm thấy: ISIC_0056492
Không tìm thấy: ISIC_0056494
Không tìm thấy: ISIC_0056513
Không tìm thấy: ISIC_0056524
Không tìm thấy: ISIC_0056553
Không tìm thấy: ISIC_0056558
Không tìm thấy: ISIC_0056561
Không tìm thấy: ISIC_0056562
Không tìm thấy: ISIC_0056568
Không tìm thấy: ISIC_0056574
Không tìm thấy: ISIC_0056587
Không tìm thấy: ISIC_0056589
Không tìm thấy: ISIC_0056597
Không tìm thấy: ISIC_0056598
Không tìm thấy: ISIC_0056627
Không tìm thấy: ISIC_0056634
Không tìm thấy: ISIC_0056637
Không tìm thấy: ISIC_0056641
Không tìm thấy: ISIC_0056642
Không tìm thấy: ISIC_0056653
Không tìm thấy: ISIC_0056667
Không tìm thấy: ISIC_0056686
Không tìm thấy: ISIC_0056716
Không tìm thấy: ISIC_0056735
Không tìm thấy: ISIC_0056744
Không tìm thấy: ISIC_0056748
Không tìm thấy: ISIC_0056758
Không tìm thấy: ISIC_0056760
Không tìm thấy: ISIC_0056776
Không tìm thấy: ISIC_0056777
Không tìm thấy: ISIC_0056781
Không tìm thấy: ISIC_0056785
Không tìm thấy: ISIC_0056792
Không tìm thấy: ISIC_0056797
Không tìm thấy: ISIC_0056801
Không tìm thấy: ISIC_0056802
Không tìm thấy: ISIC_0056804
Không tìm thấy: ISIC_0056823
Không tìm thấy: ISIC_0056833
Không tìm thấy: ISIC_0056859
Không tìm thấy: ISIC_0056864
Không tìm thấy: ISIC_0056879
Không tìm thấy: ISIC_0056892
Không tìm thấy: ISIC_0056894
Không tìm thấy: ISIC_0056910
Không tìm thấy: ISIC_0056912
Không tìm thấy: ISIC_0056931
Không tìm thấy: ISIC_0056932
Không tìm thấy: ISIC_0056944
Không tìm thấy: ISIC_0056952
Không tìm thấy: ISIC_0056955
Không tìm thấy: ISIC_0056971
Không tìm thấy: ISIC_0056975
Không tìm thấy: ISIC_0057000
Không tìm thấy: ISIC_0057001
Không tìm thấy: ISIC_0057007
Không tìm thấy: ISIC_0057012
Không tìm thấy: ISIC_0057053
Không tìm thấy: ISIC_0057078
Không tìm thấy: ISIC_0057079
Không tìm thấy: ISIC_0057084
Không tìm thấy: ISIC_0057105
Không tìm thấy: ISIC_0057109
Không tìm thấy: ISIC_0057119
Không tìm thấy: ISIC_0057120
Không tìm thấy: ISIC_0057123
Không tìm thấy: ISIC_0057137
Không tìm thấy: ISIC_0057142
Không tìm thấy: ISIC_0057158
Không tìm thấy: ISIC_0057176
Không tìm thấy: ISIC_0057181
Không tìm thấy: ISIC_0057191
Không tìm thấy: ISIC_0057194
Không tìm thấy: ISIC_0057203
Không tìm thấy: ISIC_0057217
Không tìm thấy: ISIC_0057226
Không tìm thấy: ISIC_0057229
Không tìm thấy: ISIC_0057231
Không tìm thấy: ISIC_0057243
Không tìm thấy: ISIC_0057249
Không tìm thấy: ISIC_0057265
Không tìm thấy: ISIC_0057268
Không tìm thấy: ISIC_0057270
Không tìm thấy: ISIC_0057271
Không tìm thấy: ISIC_0057301
Không tìm thấy: ISIC_0057311
Không tìm thấy: ISIC_0057320
Không tìm thấy: ISIC_0057322
Không tìm thấy: ISIC_0057325
Không tìm thấy: ISIC_0057327
Không tìm thấy: ISIC_0057335
Không tìm thấy: ISIC_0057350
Không tìm thấy: ISIC_0057363
Không tìm thấy: ISIC_0057367
Không tìm thấy: ISIC_0057376
Không tìm thấy: ISIC_0057379
Không tìm thấy: ISIC_0057382
Không tìm thấy: ISIC_0057383
Không tìm thấy: ISIC_0057389
Không tìm thấy: ISIC_0057403
Không tìm thấy: ISIC_0057416
Không tìm thấy: ISIC_0057447
Không tìm thấy: ISIC_0057452
Không tìm thấy: ISIC_0057461
Không tìm thấy: ISIC_0057466
Không tìm thấy: ISIC_0057470
Không tìm thấy: ISIC_0057476
Không tìm thấy: ISIC_0057478
Không tìm thấy: ISIC_0057490
Không tìm thấy: ISIC_0057494
Không tìm thấy: ISIC_0057507
Không tìm thấy: ISIC_0057543
Không tìm thấy: ISIC_0057546
Không tìm thấy: ISIC_0057549
Không tìm thấy: ISIC_0057555
Không tìm thấy: ISIC_0057568
Không tìm thấy: ISIC_0057581
Không tìm thấy: ISIC_0057585
Không tìm thấy: ISIC_0057588
Không tìm thấy: ISIC_0057598
Không tìm thấy: ISIC_0057599
Không tìm thấy: ISIC_0057601
Không tìm thấy: ISIC_0057603
Không tìm thấy: ISIC_0057608
Không tìm thấy: ISIC_0057624
Không tìm thấy: ISIC_0057637
Không tìm thấy: ISIC_0057644
Không tìm thấy: ISIC_0057659
Không tìm thấy: ISIC_0057663
Không tìm thấy: ISIC_0057664
Không tìm thấy: ISIC_0057667
Không tìm thấy: ISIC_0057686
Không tìm thấy: ISIC_0057689
Không tìm thấy: ISIC_0057719
Không tìm thấy: ISIC_0057733
Không tìm thấy: ISIC_0057761
Không tìm thấy: ISIC_0057766
Không tìm thấy: ISIC_0057767
Không tìm thấy: ISIC_0057772
Không tìm thấy: ISIC_0057773
Không tìm thấy: ISIC_0057775
Không tìm thấy: ISIC_0057776
Không tìm thấy: ISIC_0057780
Không tìm thấy: ISIC_0057788
Không tìm thấy: ISIC_0057795
Không tìm thấy: ISIC_0057800
Không tìm thấy: ISIC_0057807
Không tìm thấy: ISIC_0057830
Không tìm thấy: ISIC_0057833
Không tìm thấy: ISIC_0057846
Không tìm thấy: ISIC_0057856
Không tìm thấy: ISIC_0057895
Không tìm thấy: ISIC_0057907
Không tìm thấy: ISIC_0057912
Không tìm thấy: ISIC_0057934
Không tìm thấy: ISIC_0057948
Không tìm thấy: ISIC_0057951
Không tìm thấy: ISIC_0057961
Không tìm thấy: ISIC_0057971
Không tìm thấy: ISIC_0057993
Không tìm thấy: ISIC_0058002
Không tìm thấy: ISIC_0058004
Không tìm thấy: ISIC_0058013
Không tìm thấy: ISIC_0058017
Không tìm thấy: ISIC_0058019
Không tìm thấy: ISIC_0058045
Không tìm thấy: ISIC_0058048
Không tìm thấy: ISIC_0058052
Không tìm thấy: ISIC_0058066
Không tìm thấy: ISIC_0058077
Không tìm thấy: ISIC_0058082
Không tìm thấy: ISIC_0058086
Không tìm thấy: ISIC_0058093
Không tìm thấy: ISIC_0058095
Không tìm thấy: ISIC_0058100
Không tìm thấy: ISIC_0058107
Không tìm thấy: ISIC_0058112
Không tìm thấy: ISIC_0058121
Không tìm thấy: ISIC_0058131
Không tìm thấy: ISIC_0058133
Không tìm thấy: ISIC_0058134
Không tìm thấy: ISIC_0058140
Không tìm thấy: ISIC_0058175
Không tìm thấy: ISIC_0058182
Không tìm thấy: ISIC_0058189
Không tìm thấy: ISIC_0058190
Không tìm thấy: ISIC_0058200
Không tìm thấy: ISIC_0058205
Không tìm thấy: ISIC_0058207
Không tìm thấy: ISIC_0058213
Không tìm thấy: ISIC_0058225
Không tìm thấy: ISIC_0058243
Không tìm thấy: ISIC_0058247
Không tìm thấy: ISIC_0058250
Không tìm thấy: ISIC_0058253
Không tìm thấy: ISIC_0058258
Không tìm thấy: ISIC_0058279
Không tìm thấy: ISIC_0058280
Không tìm thấy: ISIC_0058287
Không tìm thấy: ISIC_0058290
Không tìm thấy: ISIC_0058291
Không tìm thấy: ISIC_0058294
Không tìm thấy: ISIC_0058326
Không tìm thấy: ISIC_0058336
Không tìm thấy: ISIC_0058343
Không tìm thấy: ISIC_0058345
Không tìm thấy: ISIC_0058365
Không tìm thấy: ISIC_0058371
Không tìm thấy: ISIC_0058373
Không tìm thấy: ISIC_0058396
Không tìm thấy: ISIC_0058398
Không tìm thấy: ISIC_0058402
Không tìm thấy: ISIC_0058403
Không tìm thấy: ISIC_0058422
Không tìm thấy: ISIC_0058438
Không tìm thấy: ISIC_0058440
Không tìm thấy: ISIC_0058441
Không tìm thấy: ISIC_0058454
Không tìm thấy: ISIC_0058455
Không tìm thấy: ISIC_0058456
Không tìm thấy: ISIC_0058480
Không tìm thấy: ISIC_0058488
Không tìm thấy: ISIC_0058490
Không tìm thấy: ISIC_0058498
Không tìm thấy: ISIC_0058502
Không tìm thấy: ISIC_0058516
Không tìm thấy: ISIC_0058519
Không tìm thấy: ISIC_0058522
Không tìm thấy: ISIC_0058535
Không tìm thấy: ISIC_0058545
Không tìm thấy: ISIC_0058551
Không tìm thấy: ISIC_0058554
Không tìm thấy: ISIC_0058575
Không tìm thấy: ISIC_0058595
Không tìm thấy: ISIC_0058609
Không tìm thấy: ISIC_0058613
Không tìm thấy: ISIC_0058614
Không tìm thấy: ISIC_0058626
Không tìm thấy: ISIC_0058628
Không tìm thấy: ISIC_0058638
Không tìm thấy: ISIC_0058650
Không tìm thấy: ISIC_0058671
Không tìm thấy: ISIC_0058677
Không tìm thấy: ISIC_0058685
Không tìm thấy: ISIC_0058695
Không tìm thấy: ISIC_0058705
Không tìm thấy: ISIC_0058706
Không tìm thấy: ISIC_0058725
Không tìm thấy: ISIC_0058726
Không tìm thấy: ISIC_0058727
Không tìm thấy: ISIC_0058728
Không tìm thấy: ISIC_0058739
Không tìm thấy: ISIC_0058742
Không tìm thấy: ISIC_0058771
Không tìm thấy: ISIC_0058779
Không tìm thấy: ISIC_0058789
Không tìm thấy: ISIC_0058793
Không tìm thấy: ISIC_0058796
Không tìm thấy: ISIC_0058831
Không tìm thấy: ISIC_0058834
Không tìm thấy: ISIC_0058839
Không tìm thấy: ISIC_0058844
Không tìm thấy: ISIC_0058853
Không tìm thấy: ISIC_0058855
Không tìm thấy: ISIC_0058894
Không tìm thấy: ISIC_0058899
Không tìm thấy: ISIC_0058918
Không tìm thấy: ISIC_0058921
Không tìm thấy: ISIC_0058937
Không tìm thấy: ISIC_0058948
Không tìm thấy: ISIC_0058953
Không tìm thấy: ISIC_0058955
Không tìm thấy: ISIC_0058963
Không tìm thấy: ISIC_0058968
Không tìm thấy: ISIC_0058975
Không tìm thấy: ISIC_0058981
Không tìm thấy: ISIC_0058985
Không tìm thấy: ISIC_0059003
Không tìm thấy: ISIC_0059004
Không tìm thấy: ISIC_0059021
Không tìm thấy: ISIC_0059026
Không tìm thấy: ISIC_0059048
Không tìm thấy: ISIC_0059051
Không tìm thấy: ISIC_0059059
Không tìm thấy: ISIC_0059060
Không tìm thấy: ISIC_0059061
Không tìm thấy: ISIC_0059083
Không tìm thấy: ISIC_0059084
Không tìm thấy: ISIC_0059125
Không tìm thấy: ISIC_0059127
Không tìm thấy: ISIC_0059133
Không tìm thấy: ISIC_0059154
Không tìm thấy: ISIC_0059156
Không tìm thấy: ISIC_0059173
Không tìm thấy: ISIC_0059175
Không tìm thấy: ISIC_0059189
Không tìm thấy: ISIC_0059197
Không tìm thấy: ISIC_0059225
Không tìm thấy: ISIC_0059234
Không tìm thấy: ISIC_0059238
Không tìm thấy: ISIC_0059244
Không tìm thấy: ISIC_0059247
Không tìm thấy: ISIC_0059249
Không tìm thấy: ISIC_0059251
Không tìm thấy: ISIC_0059259
Không tìm thấy: ISIC_0059261
Không tìm thấy: ISIC_0059271
Không tìm thấy: ISIC_0059279
Không tìm thấy: ISIC_0059282
Không tìm thấy: ISIC_0059283
Không tìm thấy: ISIC_0059286
Không tìm thấy: ISIC_0059288
Không tìm thấy: ISIC_0059293
Không tìm thấy: ISIC_0059296
Không tìm thấy: ISIC_0059302
Không tìm thấy: ISIC_0059309
Không tìm thấy: ISIC_0059311
Không tìm thấy: ISIC_0059328
Không tìm thấy: ISIC_0059339
Không tìm thấy: ISIC_0059355
Không tìm thấy: ISIC_0059406
Không tìm thấy: ISIC_0059409
Không tìm thấy: ISIC_0059425
Không tìm thấy: ISIC_0059430
Không tìm thấy: ISIC_0059459
Không tìm thấy: ISIC_0059492
Không tìm thấy: ISIC_0059499
Không tìm thấy: ISIC_0059507
Không tìm thấy: ISIC_0059508
Không tìm thấy: ISIC_0059518
Không tìm thấy: ISIC_0059530
Không tìm thấy: ISIC_0059542
Không tìm thấy: ISIC_0059550
Không tìm thấy: ISIC_0059555
Không tìm thấy: ISIC_0059574
Không tìm thấy: ISIC_0059584
Không tìm thấy: ISIC_0059586
Không tìm thấy: ISIC_0059594
Không tìm thấy: ISIC_0059645
Không tìm thấy: ISIC_0059652
Không tìm thấy: ISIC_0059667
Không tìm thấy: ISIC_0059672
Không tìm thấy: ISIC_0059683
Không tìm thấy: ISIC_0059712
Không tìm thấy: ISIC_0059723
Không tìm thấy: ISIC_0059732
Không tìm thấy: ISIC_0059734
Không tìm thấy: ISIC_0059740
Không tìm thấy: ISIC_0059779
Không tìm thấy: ISIC_0059798
Không tìm thấy: ISIC_0059817
Không tìm thấy: ISIC_0059822
Không tìm thấy: ISIC_0059837
Không tìm thấy: ISIC_0059856
Không tìm thấy: ISIC_0059858
Không tìm thấy: ISIC_0059880
Không tìm thấy: ISIC_0059893
Không tìm thấy: ISIC_0059895
Không tìm thấy: ISIC_0059900
Không tìm thấy: ISIC_0059901
Không tìm thấy: ISIC_0059902
Không tìm thấy: ISIC_0059909
Không tìm thấy: ISIC_0059934
Không tìm thấy: ISIC_0059936
Không tìm thấy: ISIC_0059955
Không tìm thấy: ISIC_0059956

In [19]:
# Lọc bỏ các hàng có UNK = 1 (giữ lại UNK = 0)
df_filtered = df[df['UNK'] == 0].copy()
print(f"Số lượng ảnh sau khi lọc UNK: {len(df_filtered)}")

Số lượng ảnh sau khi lọc UNK: 6191

In [20]:
# Lưu file metadata đã xử lý
output_path = 'data/raw/ISIC_2019_Test_Metadata_Clean.csv'
os.makedirs(os.path.dirname(output_path), exist_ok=True)
df_filtered.to_csv(output_path, index=False)
print(f"Đã lưu file metadata tại: {output_path}")
print(f"Tổng số mẫu: {len(df_filtered)}")

Đã lưu file metadata tại: data/raw/ISIC_2019_Test_Metadata_Clean.csv
Tổng số mẫu: 6191

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('data/raw/ISIC_2019_Test_Metadata_Clean.csv')
df

             image  MEL   NV  BCC   AK  BKL   DF  VASC  SCC  UNK
0     ISIC_0034321  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
1     ISIC_0034322  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
2     ISIC_0034323  0.0  0.0  1.0  0.0  0.0  0.0   0.0  0.0  0.0
3     ISIC_0034324  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
4     ISIC_0034325  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
...            ...  ...  ...  ...  ...  ...  ...   ...  ...  ...
6186  ISIC_0073226  0.0  0.0  1.0  0.0  0.0  0.0   0.0  0.0  0.0
6187  ISIC_0073234  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0
6188  ISIC_0073236  0.0  0.0  0.0  0.0  0.0  0.0   0.0  1.0  0.0
6189  ISIC_0073243  0.0  0.0  1.0  0.0  0.0  0.0   0.0  0.0  0.0
6190  ISIC_0073250  0.0  1.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0

[6191 rows x 10 columns]

In [6]:
df.drop(['UNK'], axis=1, inplace=True)

In [7]:
DATA_DIR = 'data/processed/cropped_lesions_testset/'

In [9]:
import os
classes = ['MEL', 'NV', 'BCC', 'AK', 'BKL', 'DF', 'VASC', 'SCC']

# Chuyển từ One-Hot Encoding sang Single Label
df['label'] = df[classes].idxmax(axis=1)
df['path'] = df['image'].apply(lambda x: os.path.join(DATA_DIR, x + '.jpg'))

print("\nDữ liệu sau khi xử lý:")
display(df[['image', 'label', 'path']].head())

print(f"Tổng số lượng mẫu: {len(df)}")

Dữ liệu sau khi xử lý:

          image label                                               path
0  ISIC_0034321    NV  data/processed/cropped_lesions_testset/ISIC_00...
1  ISIC_0034322    NV  data/processed/cropped_lesions_testset/ISIC_00...
2  ISIC_0034323   BCC  data/processed/cropped_lesions_testset/ISIC_00...
3  ISIC_0034324    NV  data/processed/cropped_lesions_testset/ISIC_00...
4  ISIC_0034325    NV  data/processed/cropped_lesions_testset/ISIC_00...

Tổng số lượng mẫu: 6191

In [10]:
df.drop(['MEL', 'NV', 'BCC', 'AK', 'BKL', 'DF', 'VASC', 'SCC'], axis=1, inplace=True)

In [11]:
df

             image label                                               path
0     ISIC_0034321    NV  data/processed/cropped_lesions_testset/ISIC_00...
1     ISIC_0034322    NV  data/processed/cropped_lesions_testset/ISIC_00...
2     ISIC_0034323   BCC  data/processed/cropped_lesions_testset/ISIC_00...
3     ISIC_0034324    NV  data/processed/cropped_lesions_testset/ISIC_00...
4     ISIC_0034325    NV  data/processed/cropped_lesions_testset/ISIC_00...
...            ...   ...                                                ...
6186  ISIC_0073226   BCC  data/processed/cropped_lesions_testset/ISIC_00...
6187  ISIC_0073234    NV  data/processed/cropped_lesions_testset/ISIC_00...
6188  ISIC_0073236   SCC  data/processed/cropped_lesions_testset/ISIC_00...
6189  ISIC_0073243   BCC  data/processed/cropped_lesions_testset/ISIC_00...
6190  ISIC_0073250    NV  data/processed/cropped_lesions_testset/ISIC_00...

[6191 rows x 3 columns]

In [13]:
# Định nghĩa danh sách các class theo thứ tự mong muốn
classes = ['MEL', 'NV', 'BCC', 'AK', 'BKL', 'DF', 'VASC', 'SCC']

# Tạo mapping từ text sang số
class_to_idx = {cls: idx for idx, cls in enumerate(classes)}
print("Mapping từ nhãn text sang số:")
for cls, idx in class_to_idx.items():
    print(f"  {cls} -> {idx}")

# Tạo cột 'target' bằng cách map cột 'label'
df['target'] = df['label'].map(class_to_idx)

# Kiểm tra kết quả
print("\nDữ liệu sau khi thêm cột target:")
display(df[['image', 'label', 'target', 'path']].head(10))

# Kiểm tra phân bố các class
print("\nPhân bố các class:")
print(df['target'].value_counts().sort_index())

Mapping từ nhãn text sang số:
  MEL -> 0
  NV -> 1
  BCC -> 2
  AK -> 3
  BKL -> 4
  DF -> 5
  VASC -> 6
  SCC -> 7

Dữ liệu sau khi thêm cột target:

,image,label,target,path
0,ISIC_0034321,NV,1,data/processed/cropped_lesions_testset/ISIC_00...
1,ISIC_0034322,NV,1,data/processed/cropped_lesions_testset/ISIC_00...
2,ISIC_0034323,BCC,2,data/processed/cropped_lesions_testset/ISIC_00...
3,ISIC_0034324,NV,1,data/processed/cropped_lesions_testset/ISIC_00...
4,ISIC_0034325,NV,1,data/processed/cropped_lesions_testset/ISIC_00...
5,ISIC_0034326,BKL,4,data/processed/cropped_lesions_testset/ISIC_00...
6,ISIC_0034328,NV,1,data/processed/cropped_lesions_testset/ISIC_00...
7,ISIC_0034329,MEL,0,data/processed/cropped_lesions_testset/ISIC_00...
8,ISIC_0034330,NV,1,data/processed/cropped_lesions_testset/ISIC_00...
9,ISIC_0034331,NV,1,data/processed/cropped_lesions_testset/ISIC_00...

Phân bố các class:
target
0    1327
1    2495
2     975
3     374
4     660
5      91
6     104
7     165
Name: count, dtype: int64

In [15]:
df.to_csv('ISIC_2019_test_metadata.csv', index=False)